name: Main workflow

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
      # Need this for any work with repository.
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
          pip install pylint
      - name: Upgrade syntax
        run: |
          pyupgrade
      - name: Make autoformatting
        run: |
          black ./
      - name: Check codestyle
        run: |
          flake8 ./
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
      - name: Build
        run: |
          make d-homework-i-run